package com.example.product.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;


@Entity // specifies that the class is an entity and is mapped to a database table
public class Product {
	
	@Id // specifies the primary key of an entity
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Autogenerated values of primary key
    private Long productId;
    
	
	@Column(name="productName", length = 50,nullable = false) // adding the column into the table
    private String productName;

    @ManyToOne
    @JoinColumn(name = "subCategoryId")
    private SubCategory subCategory;

	@Column(name="productDescription", length = 50,nullable = false)
    private String productDescription;

	@Column(name="productPrice", length = 15,nullable = false)
    private Long productPrice;

	@Column(name="productQuantity", length = 15,nullable = false)
    private int productQuantity;

	@Column(name="productImageUrl", length = 50,nullable = false)
    private String productImageUrl;
    
    
    
    
    public Product(Long productId, String productName,String productDescription, 
    		long productPrice, int productQuantity, String productImageUrl) {
		super();
		this.productId = productId;
		this.productName = productName;
		this.productDescription = productDescription;
		this.productPrice = productPrice;
		this.productQuantity = productQuantity;
		this.productImageUrl = productImageUrl;
		
	}
	

	public Product() {
		
	}    
    
	// getters and setters       

	public Long getProductId() {
		return productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}	

	public String getProductDescription() {
		return productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public long getProductPrice() {
		return productPrice;
	}

	public void setProductPrice(long productPrice) {
		this.productPrice = productPrice;
	}

	public int getProductQuantity() {
		return productQuantity;
	}

	public void setProductQuantity(int productQuantity) {
		this.productQuantity = productQuantity;
	}

	public String getProductImageUrl() {
		return productImageUrl;
	}

	public void setProductImageUrl(String productImageUrl) {
		this.productImageUrl = productImageUrl;
	}


	public String getProductName() {
		return productName;
	}


	public void setProductName(String productName) {
		this.productName = productName;
	}

}
